spring:
  datasource:
    url: jdbc:h2:mem:retail_db;DB_CLOSE_DELAY=-1;MODE=MySQL
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

app:
  jwtSecret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  jwtExpirationMs: 86400000 # 24 hours
